server:
  port: 8080
database:
  driver: mysql
  host: localhost
  port: 3306
  user: your_db_user
  password: your_db_password
  name: ginguard
jwt:
  secret_key: your_secret_key
  expire_minutes: 60
